# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build umalib

on:
  push:
    tags:
      - "v*"

jobs:
  on-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run electron:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Uma Library Desktop ${{ github.ref_name }}
          body: created by Github Actions
          draft: false
          prerelease: false
          files: ./dist_electron/umalib-win64-${{ github.ref_name }}.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  on-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Python 2.7
        uses: actions/setup-python@v4
        with:
          python-version: '2.7'
      - name: Test environment
        run: node --version && python --version && ls -la /Users/runner/hostedtoolcache/Python/2.7.18/x64/bin/python
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run electron:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHON_PATH: /Users/runner/hostedtoolcache/Python/2.7.18/x64/bin/python
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Uma Library Desktop ${{ github.ref_name }}
          files: ./dist_electron/umalib-mac-${{ github.ref_name }}.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}